# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-03-30 11:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('raw_packing_master', '0001_initial'),
        ('manufacturing_cost_master', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='costpack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_id', models.IntegerField(default=0)),
                ('multipliar', models.FloatField(default=0)),
                ('last_updated_on', models.DateTimeField(auto_now_add=True)),
                ('Raw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='raw_packing_master.raw')),
                ('cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='manufacturing_cost_master.cost')),
            ],
        ),
    ]
